apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: GitOps-Workshop
  region: ${AWS_REGION}
  version: "1.19"

cloudWatch:
    clusterLogging:
        enableTypes: ["*"]

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true

iam:
  withOIDC: true